#!/usr/bin/env python3
"""Sync bundled schemas and generated models from orbixal-data-connector.

This repo intentionally vendors a small subset of canonical contract artifacts
so connector authors can validate manifests and result envelopes locally
without importing platform-internal packages at runtime.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from textwrap import dedent


REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DIR = REPO_ROOT / "src" / "connector_author_sdk" / "generated"
SCHEMA_DIR = REPO_ROOT / "src" / "connector_author_sdk" / "_schemas"
CANONICAL_SCHEMA_PATHS = (
    ("manifest/connector_manifest.schema.json", "manifest/connector_manifest.schema.json"),
    ("package/package_metadata.schema.json", "package/package_metadata.schema.json"),
    ("results/records_envelope.schema.json", "results/records_envelope.schema.json"),
    ("results/tabular_envelope.schema.json", "results/tabular_envelope.schema.json"),
)


def detect_source_repo(explicit: str | None) -> Path:
    candidates = [
        Path(explicit).expanduser() if explicit else None,
        Path(os.environ["ORBIXAL_DATA_CONNECTOR_REPO"]).expanduser()
        if os.environ.get("ORBIXAL_DATA_CONNECTOR_REPO")
        else None,
        REPO_ROOT.parent / "orbixal-data-connector",
    ]
    for candidate in candidates:
        if candidate and (candidate / "schemas").exists():
            return candidate.resolve()
    raise SystemExit(
        "Could not locate orbixal-data-connector. "
        "Pass --source-repo or set ORBIXAL_DATA_CONNECTOR_REPO."
    )


def load_schema(source_repo: Path, *parts: str) -> dict:
    path = source_repo / "schemas" / Path(*parts)
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, content: str, *, check: bool, changed: list[str]) -> None:
    normalized = content.rstrip() + "\n"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == normalized:
        return
    changed.append(str(path.relative_to(REPO_ROOT)))
    if not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized, encoding="utf-8")


def copy_schema_files(source_repo: Path, *, check: bool, changed: list[str]) -> None:
    for source_rel, dest_rel in CANONICAL_SCHEMA_PATHS:
        source_path = source_repo / "schemas" / source_rel
        destination = SCHEMA_DIR / dest_rel
        write_text(destination, source_path.read_text(encoding="utf-8"), check=check, changed=changed)


def literal_values(values: list[object]) -> str:
    return ", ".join(repr(value) for value in values)


def render_generated_init() -> str:
    return dedent(
        """
        # Generated by scripts/sync_canonical_contracts.py. Do not edit by hand.

        from . import error_models
        from . import manifest_models
        from . import result_models
        from . import state_models

        __all__ = ["error_models", "manifest_models", "result_models", "state_models"]
        """
    )


def render_state_models(source_repo: Path) -> str:
    credential_state = load_schema(source_repo, "states", "credential_state.schema.json")
    instance_status = load_schema(source_repo, "states", "instance_status.schema.json")
    health_status = load_schema(source_repo, "states", "health_status.schema.json")
    return dedent(
        f"""
        # Generated from canonical contract schemas. Do not edit by hand.

        from typing import Literal

        CredentialState = Literal[{literal_values(credential_state["enum"])}]
        InstanceStatus = Literal[{literal_values(instance_status["enum"])}]
        HealthStatus = Literal[{literal_values(health_status["enum"])}]
        """
    )


def render_error_models(source_repo: Path) -> str:
    schema = load_schema(source_repo, "errors", "error.schema.json")
    required = schema["properties"]["error"]["required"]
    return dedent(
        f"""
        # Generated from canonical contract schemas. Do not edit by hand.

        from typing import Any, TypedDict


        class ErrorPayload(TypedDict):
            code: str
            message: str
            retryable: bool
            request_id: str
            details: dict[str, Any]


        class ErrorEnvelope(TypedDict):
            error: ErrorPayload


        ERROR_REQUIRED_FIELDS = {required!r}
        """
    )


def render_manifest_models(source_repo: Path) -> str:
    schema = load_schema(source_repo, "manifest", "connector_manifest.schema.json")
    required = schema["required"]
    operation_kinds = schema["properties"]["operations"]["items"]["properties"]["kind"]["enum"]
    auth_type_values = schema["properties"]["auth_schema"]["properties"]["type"]["enum"]
    return dedent(
        f"""
        # Generated from canonical contract schemas. Do not edit by hand.

        from typing import Any, Literal, TypedDict


        class AuthSchemaDescriptor(TypedDict, total=False):
            type: Literal[{literal_values(auth_type_values)}]
            required_fields: list[str]
            optional_fields: list[str]


        class OperationDefinition(TypedDict, total=False):
            name: str
            kind: Literal[{literal_values(operation_kinds)}]
            input_schema: dict[str, Any]
            output_schema: dict[str, Any]


        class ConnectorManifest(TypedDict):
            key: str
            name: str
            version: str
            manifest_schema_version: str
            sdk_version: str
            runtime_compatibility_range: str
            capabilities: list[str]
            auth_schema: AuthSchemaDescriptor
            config_schema: dict[str, Any]
            resource_types: list[str]
            operations: list[OperationDefinition]


        MANIFEST_REQUIRED_FIELDS = {required!r}
        """
    )


def render_result_models(source_repo: Path) -> str:
    records_schema = load_schema(source_repo, "results", "records_envelope.schema.json")
    tabular_schema = load_schema(source_repo, "results", "tabular_envelope.schema.json")
    records_kind = records_schema["properties"]["kind"]["const"]
    tabular_kind = tabular_schema["properties"]["kind"]["const"]
    entitlement_schema = records_schema["properties"]["meta"]["properties"]["entitlement"]["properties"]
    entitlement_required = set(
        records_schema["properties"]["meta"]["properties"]["entitlement"]["required"]
    )

    def entitlement_field_type(field_name: str, schema: dict) -> str:
        field_type = schema.get("type")
        if field_type == "boolean":
            return "bool"
        return "str"

    entitlement_lines = [
        f"    {field_name}: {entitlement_field_type(field_name, field_schema)}"
        for field_name, field_schema in entitlement_schema.items()
    ]

    lines = [
        "# Generated from canonical contract schemas. Do not edit by hand.",
        "",
        "from typing import Any, Literal, TypedDict",
        "",
        "",
        "class EntitlementDescriptor(TypedDict, total=False):",
        *entitlement_lines,
        "",
        "",
        "class RecordItem(TypedDict, total=False):",
        "    id: str",
        "    type: str",
        "    title: str | None",
        "    content: dict[str, Any]",
        "    attributes: dict[str, Any]",
        "    timestamps: dict[str, Any]",
        "    source: dict[str, Any]",
        "",
        "",
        "class RecordsMeta(TypedDict):",
        "    connector_key: str",
        "    connector_version: str",
        "    action: str",
        "    request_id: str",
        "    entitlement: EntitlementDescriptor | None",
        "",
        "",
        "class RecordsEnvelope(TypedDict, total=False):",
        f"    kind: Literal[{records_kind!r}]",
        "    records: list[RecordItem]",
        "    cursor: str | None",
        "    meta: RecordsMeta",
        "    raw: dict[str, Any]",
        "",
        "",
        "class ColumnDef(TypedDict):",
        "    name: str",
        "    type: str",
        "",
        "",
        "class RowItem(TypedDict):",
        "    row_id: str",
        "    values: dict[str, Any]",
        "",
        "",
        "class TabularMeta(TypedDict):",
        "    connector_key: str",
        "    connector_version: str",
        "    action: str",
        "    request_id: str",
        "    entitlement: EntitlementDescriptor | None",
        "",
        "",
        "class TabularEnvelope(TypedDict, total=False):",
        f"    kind: Literal[{tabular_kind!r}]",
        "    columns: list[ColumnDef]",
        "    rows: list[RowItem]",
        "    cursor: str | None",
        "    meta: TabularMeta",
        "    raw: dict[str, Any]",
        "",
        "",
        f"ENTITLEMENT_REQUIRED_FIELDS = {sorted(entitlement_required)!r}",
    ]
    return "\n".join(lines)


def generate_files(source_repo: Path, *, check: bool, changed: list[str]) -> None:
    outputs = {
        GENERATED_DIR / "__init__.py": render_generated_init(),
        GENERATED_DIR / "error_models.py": render_error_models(source_repo),
        GENERATED_DIR / "manifest_models.py": render_manifest_models(source_repo),
        GENERATED_DIR / "result_models.py": render_result_models(source_repo),
        GENERATED_DIR / "state_models.py": render_state_models(source_repo),
    }
    for path, content in outputs.items():
        write_text(path, content, check=check, changed=changed)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-repo",
        help="Path to the orbixal-data-connector repository. "
        "Defaults to ORBIXAL_DATA_CONNECTOR_REPO or ../orbixal-data-connector.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if bundled schemas or generated models are out of sync.",
    )
    args = parser.parse_args()

    source_repo = detect_source_repo(args.source_repo)
    changed: list[str] = []

    copy_schema_files(source_repo, check=args.check, changed=changed)
    generate_files(source_repo, check=args.check, changed=changed)

    if args.check and changed:
        print("Out-of-sync contract artifacts:")
        for path in changed:
            print(f" - {path}")
        return 1

    if changed:
        print(f"Synchronized {len(changed)} contract artifacts from {source_repo}")
        for path in changed:
            print(f" - {path}")
    else:
        print(f"Contract artifacts already up to date with {source_repo}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
